### ISSUE TITLE
ESD in Variants not working

### ISSUE THREAD

**Issue by MoppieMop** [Shape-and-Shift/shopware-esd#13]
In my SW v6.3.5.1 I have books as products and I want to use the variants for ebooks. So my main product is no ESD and my variant is ESD (without serial).
But the ESDs are not visible under Downloads when the product is paid. 
When I set the main product as ESD everything is working as expected.

**Comment by hungmac-sw** [comment]
@MoppieMop Could you tell me your ESD version. I have tested and it works on latest versions 1.3.3 and 1.4.1

**Comment by ChristopherDosin** [comment]
I will close the issue because of inactivity. @MoppieMop feel free to re-open it if you're having still an issue.
