### ISSUE TITLE
Free to use?

### ISSUE THREAD

**Issue by NiklasTeich** [Shape-and-Shift/shopware-esd#22]
Hey folks!

Is this plugin free to use because it's public and not described otherwise?
There is no interest in extending/selling/whatever it, only using (i planned to setup a site for my personal band project)

So long!
Niklas

**Comment by ChristopherDosin** [comment]
Hi Niklas - The plugin is open source and available on GitHub, however, you still need a license to use it in production:
https://store.shopware.com/sas9155591716916/esd/downloads-fuer-shopware-6.html

Was too much work to release it for free 😅
