### ISSUE TITLE
Unable to sort by "Assigned Client" in Admin Panel

### ISSUE THREAD

**Issue by preeyamma** [Shape-and-Shift/shopware-esd#31]
Hi,

ESD Sort does not seem to work.
Issue Description / Steps to Reproduce:

1.) Go to the product
2) Click on ESD and go to Serial keys Added
3) Click on "Assigned client" or Arrow next to it and nothing happens.

Also placed a ticket at shopware.com (Ticket ID: SAS-192118) but no response.

Kindly let me know if you need any info.

**Comment by ChristopherDosin** [comment]
Good Morning @preeyamma - Thanks for the report. 
We were able to re-produce this issue and currently fixing it.

**Comment by preeyamma** [comment]
Thank you so much :)

**Comment by preeyamma** [comment]
Hi,

I added the fix and the whole client name is blank now.

**Comment by hungmac-sw** [comment]
@preeyamma In my case, it showed the client's name https://www.loom.com/share/94c177d6f9974087bf342da3fc8d7941
Do you see any errors within developer tools?

**Comment by preeyamma** [comment]
Yes. It worked. We had made some changes from our side so  it didnt work earlier. Totally our mistake.

Thanks for the fix.
