### ISSUE TITLE
Automatic Stock Increase

### ISSUE THREAD

**Issue by preeyamma** [Shape-and-Shift/shopware-esd#33]
Hi,

I just wanted to know if you have plans to update the Stock number when you add New ESD Serial Numbers i.e if i add 3 Serial Niumbers the Instock will increase by 3.

**Comment by ChristopherDosin** [comment]
@hungmac-sw Do we have any plans to do so?

**Comment by hungmac-sw** [comment]
That is a good idea. We will make it. 

We have to make a modal to select the option to update the stock number if someone doesn't want to update the stock. If the user clicks on the option, it will also update the stock number.
also, for the case, delete the serial

**Comment by preeyamma** [comment]
that would be really great.

**Comment by preeyamma** [comment]
Hi,

While you are taking enhancement requests. Please let me know if you can add another one:
1) Manually Assigna. serial key to a customer/order
