### ISSUE TITLE
Downloads broken?

### ISSUE THREAD

**Issue by DaveWoody** [Shape-and-Shift/shopware-esd#36]
Hi, i am testing this plugin and bumping into this issue.
When i am trying to download the bought file under Account -> Downloads and trying to unpack the zip it gives me an error:

![fSq4t4e](https://user-images.githubusercontent.com/5037624/155516467-1bccd5f1-25da-4833-99a6-443383deef85.png)

Basically: The zip folder is invalid. Also when i am trying to download it over Account -> Orders -> Download File i get a Download.htm which is empty.

Tested on 2 Shopware instances. Shopware 6.4.3.1 &  6.4.8.1 

ESD Version: 1.5.1

**Comment by ChristopherDosin** [comment]
@hungmac-sw Could you please have a look at this usse?

**Comment by ChristopherDosin** [comment]
@DaveWoody We can't re-produce it locally. Maybe it's an issue with another plugin.
To check this could you please do the following?

- rename .zip to .txt of the downloaded file
- open the .txt by notepad or anything else
- check if it shows a Symforny error messages, to know exactly where the error is coming from
