### ISSUE TITLE
Error message when activating by uploading the ZIP file.

### ISSUE THREAD

**Issue by gseilheimer** [Shape-and-Shift/shopware-esd#49]
I would be happy to use this extension for my students in a workshop. For simplified installation it would be purposeful if simply the ZIP file could be imported.

Unfortunately, there is the following error message in the current version of Shopware during activation.
Unable to compile the theme "Storefront". `../../node_modules/plyr/src/sass/plyr` file not found for @import: /var/www/vhosts/www01.bw.hs-offenburg.de/httpdocs/units/sw99/custom/plugins/shopware-esd-1.5.2/src/Resources/app/storefront/src/scss/base.scss on line 2, at column 1 Call Stack: #0 import /var/www/vhosts/www01.bw.hs-offenburg.de/httpdocs/units/sw99/custom/plugins/shopware-esd-1.5.2/src/Resources/app/storefront/src/scss/base.scss (unknown file) on line 30

**Comment by hungmac-sw** [comment]
@gseilheimer Sorry about my late reply, If you're running the project by `watch`, you have to run `npm install --save @plyr` within `custom/plugins/shopware-esd/src/Resources/app/storefront` or `npm install`
