### ISSUE TITLE
Error When applying promotional code

### ISSUE THREAD

**Issue by preeyamma** [Shape-and-Shift/shopware-esd#59]
Hello,

I recently updated the plugin release 1.5.3 on shopware 6.4.13.0 and found it does not allow promotional codes to be added to cart due to an error from the plugin.

Steps to produce the issue :

1)  Install latest release 1.5.3 on Shopware 6.4.13.0
2)  Add products to checkout.
3) Add a coupon code

You will see the error "Unfortunately, something went wrong."

When you disable the plugin. The coupon code is applied successfully.

Kindly help.

Regards,
Preeya

**Comment by ChristopherDosin** [comment]
@hungmac-sw could you please have a look at this issue?

**Comment by hungmac-sw** [comment]
I will close this issue because we fixed it on v1.5.4
