### ISSUE TITLE
only public file system implemented for file downloads

### ISSUE THREAD

**Issue by petermuenstermann** [Shape-and-Shift/shopware-esd#64]
(at least) in the file `custom/plugins/SasEsd/src/Service/EsdService.php` on line 403:
As you are marking the ESD media files as privat, they are stored in the /files folder and not in the /media folder.

But then, you need to use the filesystemPrivate object to fetch the files for download.

**Comment by ChristopherDosin** [comment]
@hungmac-sw Please take a look at the issue.

**Comment by hungmac-sw** [comment]
I closed this issue because we fixed it in ESD v1.6.0 https://github.com/Shape-and-Shift/shopware-esd/releases/tag/1.6.0
