### ISSUE TITLE
Downloading an item without an account

### ISSUE THREAD

**Issue by Capenus** [Shape-and-Shift/shopware-esd#7]
Currently a customer can buy a download product, but he can not download it if he was not previously registered and logged into the store.

Is it possible to send the customer a download link via e-mail or to enable the download via the temporary customer profile (e.g.: /account/order/mUVnw5oa9cPvTr05GeNnOi1OSC3r9Ja9)?

**Comment by ChristopherDosin** [comment]
Hi @Capenus 

you're right - currently, guest downloads are not possible, but we're already working on such a feature that is almost finished. 

The update will also include that you can set a limit for downloads and a custom email templates ( for downloads & serials ) will also be sent if an ESD was purchased.

I hope that we can release the version at the end of the week. If not this week, it will be next week.

**Comment by Capenus** [comment]
That sounds great, thank you very much.

**Comment by ChristopherDosin** [comment]
Hey @Capenus 

we released[ version 1.2.0](https://github.com/Shape-and-Shift/shopware-esd/releases/tag/1.2.0) which includes also guest downloads.

The release is also available within the store. Make sure to assign the `ESD Download` Email template your Saleschannel.

**Comment by Capenus** [comment]
Thank you @ChristopherDosin!
