### ISSUE TITLE
Privacy Policy and Terms of Use

### ISSUE THREAD

**Issue by SilkeVogel** [Shape-and-Shift/shopware-esd#72]
Dear Sir or Madam,

we would like to purchase your Shopware "ESD plugin". Could you please let me know, where I can find your privacy policy and terms of use? Where is the plugin hosted? And will shapeandshift or anyone else have access to the data collected via the "ESD plugin"?

Thank you and best regards,
Silke Hoeffken

**Comment by ChristopherDosin** [comment]
I will close this issue since it was clarified via LinkedIn message.
For all others: We do not sure any data. All files are stored on your server, just as any other media file.

Because all ESD files are private you just can't see them within your media manager - The same as documents etc.
